#!/bin/bash

# repo directory
repo_dir="dotfiles"

# home directories
home_dirs=("Templates")

# config directory items
config_dir=".config"
conf_dirs=("ags" "dunst" "hypr" "kitty" "lf" "macchina" "udiskie" "waybar" "labwc" "niri" "river" "sway" "wayfire")
conf_files=("background")

# root directory items
root_dirs=("/etc/greetd/" "/usr/share/backgrounds/")

if [ $1 = "backup" ]; then
	cd ~

	# copying home folders
	for element in "${home_dirs[@]}"; do
		echo "Copying ~/${element} to ~/${repo_dir}/home/${element}"
		cp -r $element ~/${repo_dir}/home/
	done
	
	cd ~/${config_dir}
	
	# copying .config folders
	for element in "${conf_dirs[@]}"; do
		echo "Copying ~/${config_dir}/${element} to ~/${repo_dir}/home/config/${element}"
		cp -r $element ~/${repo_dir}/home/config/
	done
	
	# copying .config files
	for element in "${conf_files[@]}"; do
		echo "Copying ~/${config_dir}/${element} to ~/${repo_dir}/home/config/${element}"
		cp $element ~/${repo_dir}/home/config/
	done

	cd ~
	
	# copying folders from root
	for element in "${root_dirs[@]}"; do
		echo "Copying ${element} to ~/${repo_dir}/root${element}"
		cp -r $element ~/${repo_dir}/root/
	done

elif [ $1 = "install" ]; then
	cd ~
	
	# installing home folders
	cd $config_dir
        for element in "${home_dirs[@]}"; do
		echo "Copying ~/${repo_dir}/home/${element} to ~${element}"
		cp -r ~/${repo_dir}/home/${element} ~/
	done

	# installing home config folders
	for element in "${conf_dirs[@]}"; do
		echo "Copying ~/${repo_dir}/home/config/${element} to ~/${config_dir}/${element}"
		cp -r ~/${repo_dir}/home/config/${element} ~/${config_dir}/
	done

	# installing home config files
	for element in "${conf_files[@]}"; do
		echo "Copying ~/${repo_dir}/home/config/${element} to ~/${config_dir}/${element}"
		cp ~/${repo_dir}/home/config/${element} ~/${config_dir}/
	done

	cd ~

	echo "!!! THIS SCRIPT AVOIDS INSTALLING TO THE ROOT DIRECTORY ON PURPOSE, DON'T FORGET TO COPY THOSE CONFIGS OVER MANUALLY !!!"
else
	echo "Usage: dotfiles [arg]"
	echo
	echo "Valid arguments:"
	echo "backup - backs up files from specified directories in the script to the repo"
	echo "install - copies files from the repo to their respective directories [!!! AVOIDS MODIFYING ROOT DIRS ON PURPOSE !!!]"

fi
