color0 #111a2c
color1 #fd4663
color2 #6790e4
color3 #715cd6
color4 #aa66cc
color5 #93b0ec
color6 #a496e9
color7 #f2f2f3
color8 #5f6673
color9 #fd4663
color10 #6790e4
color11 #715cd6
color12 #aa66cc
color13 #93b0ec
color14 #a496e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #111a2c
background            #111a2c
foreground            #f2f2f3
selection_foreground  #afb1b6
selection_background  #17233b
active_border_color   #6790e4
inactive_border_color #17233b
url_color             #6790e4
